global:
  scrape_interval: 10s
  evaluation_interval: 10s
# See https://github.com/samber/awesome-prometheus-alerts for more alert ideas.
rule_files: ["/prometheus/rules/*.yml"]
alerting:
  alertmanagers:
  - static_configs:
    - targets: ["alertmanager:9093"]
# Try to keep the same order and format as the Helm chart to make it easy to track changes.
scrape_configs:
# Cadvisor metrics (https://kubernetes.default.svc:443/api/v1/nodes/$host_name/proxy/metrics/cadvisor)
- job_name: kubernetes-cadvisor-metrics
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - replacement: kubernetes.default.svc:443
    target_label: __address__
  - regex: (.+)
    replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
    source_labels: ["__meta_kubernetes_node_name"]
    target_label: __metrics_path__
  scheme: https
  tls_config:
    insecure_skip_verify: true
# Endpoint metrics (http://$service_address:$service_port/metrics)
- job_name: kubernetes-endpoint-metrics
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: true
    source_labels: ["__meta_kubernetes_service_annotation_prometheus_io_scrape"]
  - action: replace
    regex: (https?)
    source_labels: ["__meta_kubernetes_service_annotation_prometheus_io_scheme"]
    target_label: __scheme__
  - action: replace
    regex: (.+)
    source_labels: ["__meta_kubernetes_service_annotation_prometheus_io_path"]
    target_label: __metrics_path__
  - action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    source_labels: ["__address__", "__meta_kubernetes_service_annotation_prometheus_io_port"]
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - action: replace
    source_labels: ["__meta_kubernetes_namespace"]
    target_label: kubernetes_namespace
  - action: replace
    source_labels: ["__meta_kubernetes_service_name"]
    target_label: kubernetes_name
  - action: replace
    source_labels: ["__meta_kubernetes_pod_node_name"]
    target_label: kubernetes_node
# Service probes (http://blackbox-exporter:9115/probe?target=$instance&module=http_2xx)
- job_name: kubernetes-service-probes
  kubernetes_sd_configs:
  - role: service
  metrics_path: /probe
  params:
    module: ["http_2xx"]
  relabel_configs:
  - action: keep
    regex: true
    source_labels: ["__meta_kubernetes_service_annotation_prometheus_io_probe"]
  - source_labels: ["__address__"]
    target_label: __param_target
  - replacement: blackbox-exporter:9115
    target_label: __address__
  - source_labels: ["__param_target"]
    target_label: instance
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels: ["__meta_kubernetes_namespace"]
    target_label: kubernetes_namespace
  - source_labels: ["__meta_kubernetes_service_name"]
    target_label: kubernetes_name
# Pod metrics (http://$pod_address:$pod_port/metrics)
- job_name: kubernetes-pod-metrics
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: keep
    regex: true
    source_labels: ["__meta_kubernetes_pod_annotation_prometheus_io_scrape"]
  - action: replace
    regex: (.+)
    source_labels: ["__meta_kubernetes_pod_annotation_prometheus_io_path"]
    target_label: __metrics_path__
  - action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    source_labels: ["__address__", "__meta_kubernetes_pod_annotation_prometheus_io_port"]
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    source_labels: ["__meta_kubernetes_namespace"]
    target_label: kubernetes_namespace
  - action: replace
    source_labels: ["__meta_kubernetes_pod_name"]
    target_label: kubernetes_pod_name
  - action: keep
    regex: 9\d{3}
    source_labels: ["__meta_kubernetes_pod_container_port_number"]
