---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app: alertmanager
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/probe: 'true'
spec:
  selector:
    app: alertmanager
  ports:
  - name: http
    port: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.19.0
        imagePullPolicy: IfNotPresent
        resources:
          requests: {}
          limits: {}
        args:
        - --config.file=/alertmanager/alertmanager.yml
        - --storage.path=/data
        - --data.retention=24h
        ports:
        - name: http
          containerPort: 9093
        readinessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 30
          httpGet:
            path: /#/status
            port: 9093
        volumeMounts:
        - name: alertmanager-config
          mountPath: /alertmanager
        - name: alertmanager-data
          mountPath: /data
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
      - name: alertmanager-data
        emptyDir: {}
