---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: monitoring-system
  labels:
    app: promtail
---
# https://github.com/grafana/loki/blob/v1.0.0/production/helm/promtail/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: promtail
  labels:
    app: promtail
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: promtail
  labels:
    app: promtail
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: promtail
subjects:
- kind: ServiceAccount
  name: promtail
  namespace: monitoring-system
---
apiVersion: v1
kind: Service
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  clusterIP: None
  selector:
    app: promtail
  ports:
  - name: http
    port: 3101
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      tolerations:
      - operator: Exists
      containers:
      - name: promtail
        image: grafana/promtail:v1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests: {}
          limits: {}
        securityContext:
          readOnlyRootFilesystem: true
          runAsGroup: 0
          runAsUser: 0
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            path: /ready
            port: 3101
        args:
        - -config.file=/etc/promtail/promtail.yaml
        - -client.url=http://loki:3100/loki/api/v1/push
        ports:
        - name: http
          containerPort: 3101
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail
        - name: run
          mountPath: /run/promtail
        - mountPath: /var/lib/docker/containers
          name: docker
          readOnly: true
        - mountPath: /var/log/pods
          name: pods
          readOnly: true
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-config
      - name: run
        hostPath:
          path: /run/promtail
      - name: docker
        hostPath:
          path: /var/lib/docker/containers
      - name: pods
        hostPath:
          path: /var/log/pods
