# https://github.com/grafana/loki/blob/v1.1.0/production/helm/loki/values.yaml#L21
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      replication_factor: 1
      kvstore:
        store: inmemory
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: '2018-04-15'
    object_store: filesystem
    schema: v9
    store: boltdb
    index:
      period: 168h
      prefix: index_
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: /data/loki/index
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: false
  retention_period: 0
