# https://awesome-prometheus-alerts.grep.to/rules#blackbox
groups:
- name: Probe
  rules:
  - alert: ProbeFailed
    labels:
      severity: page
    expr: probe_success == 0
    for: 1m
    annotations:
      summary: "Probe failed (instance {{ $labels.instance }})"
      description: |-
        Probe failed
          VALUE = {{ $value }}
          LABELS: {{ $labels }}
  - alert: ProbeHttpStatusCode
    expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
    for: 1m
    labels:
      severity: page
    annotations:
      summary: "HTTP Status Code (instance {{ $labels.instance }})"
      description: |-
        HTTP status code is not 200-399
          VALUE = {{ $value }}
          LABELS: {{ $labels }}
